kkebo/zyphy

Sources/Tokenizer/State.swift, Sources/Tokenizer/Tokenizer.swift
=> refactor: shorten state names

.github/workflows/swift.yml
The job "build-linux" takes about 10 minutes. It's so slow. I hope that using caches makes it faster.
=> ci: use build caches

Benchmarks/Package.swift
SwiftPM always uses `Package.resolved` when building an application, so I realized that `.upToNextMinor` was stricter than necessary.
=> build: loosen versoin constraints

Benchmarks/Package.resolved, Benchmarks/Package.swift
https://github.com/ordo-one/package-benchmark/releases/tag/1.12.0
=> build: bump package-benchmark to 1.12.0

Sources/Tokenizer/CharRefTokenizer.swift, Sources/Tokenizer/Character+firstScalar.swift, Sources/Tokenizer/Tokenizer.swift, Sources/Tokenizer/Utils.swift
The following computed properties call computed properties of `Unicode.Scalar.Properties`.
- https://github.com/apple/swift/blob/98e65d015979c7b5a58a6ecf2d8598a6f7c85794/stdlib/public/core/CharacterProperties.swift#L27
- https://github.com/apple/swift/blob/98e65d015979c7b5a58a6ecf2d8598a6f7c85794/stdlib/public/core/CharacterProperties.swift#L117
- https://github.com/apple/swift/blob/98e65d015979c7b5a58a6ecf2d8598a6f7c85794/stdlib/public/core/CharacterProperties.swift#L149
- https://github.com/apple/swift/blob/98e65d015979c7b5a58a6ecf2d8598a6f7c85794/stdlib/public/core/CharacterProperties.swift#L199
- https://github.com/apple/swift/blob/98e65d015979c7b5a58a6ecf2d8598a6f7c85794/stdlib/public/core/CharacterProperties.swift#L252
However, those computed properties call a computed property …
=> perf: avoid `Unicode.Scalar.Properties`

Benchmarks/Package.resolved, Benchmarks/Package.swift
https://github.com/ordo-one/package-benchmark/releases/tag/1.18.0
=> build: bump package-benchmark to 1.18.0

.github/workflows/swift.yml
I commented out the cache action because it caused a build error, but I want to re-enable it to make running jobs faster.
I've created this pull request so that I can watch until the build error is fixed in the latest toolchain.
=> ci: re-enable cache action

.github/workflows/swift.yml, .swift-format, Benchmarks/Package.resolved, Benchmarks/Package.swift, Package.resolved, Package.swift
I have been using swift-format as a SwiftPM plugin since #14, but swift-format seems to be included in the recent main snapshot toolchain, so I decided to use that one.
This will speed up CI.
=> build: use builtin swift-format

Benchmarks/Package.resolved, Benchmarks/Package.swift
https://github.com/ordo-one/package-benchmark/releases/tag/1.22.2
=> build(benchmark): bump package-benchmark to 1.22.2

Benchmarks/Package.swift, Package.resolved, Package.swift
Swift 5.11 is now Swift 6.0. When the development snapshot CI is passed next time, we should be able to change `swift-tools-version` to `6.0`.
=> build: bump swift-tools-version to 6.0

Sources/HTMLEntities/namedChars.swift, Sources/Tokenizer/CharRefTokenizer.swift, Sources/Tokenizer/Tokenizer.swift, Sources/TokenizerMacros/Macros.swift, Tests/TokenizerTests/HTML5LibTests.swift
I've implemented `CharRefTokenizer`.
```console
$ swift package --package-path Benchmarks benchmark baseline compare main
warning: 'package-benchmark': Jemalloc disabled through environment variable.
Building for debugging...
[9/9] Emitting module BenchmarkBoilerplateGenerator
Build of product 'BenchmarkBoilerplateGenerator' complete! (1.32s)
Building for debugging...
[1/1] Write swift-version--FC39A71C9A0968F.txt
Build of product 'BenchmarkTool' complete! (2.12s)
Build complete!
Building BenchmarkTool in release mode...
Building benchmark targets in release mode for benchmark run...
Building MyBenchmark
==================
Running Benchmarks
==================
100% [------------------------------------------------------------] ETA: 00:00:00 | MyBenchmark:TokenizerBenchmark …
```
=> feat: implement CharRefTokenizer

.github/workflows/swift.yml
I already updated README.md so that we use 6.0-snapshot, so I should use
nightly-6.0-jammy in CI too.
=> ci: change the swiftlang/swift image from nightly-main-jammy to nightly-6.0-jammy

Benchmarks/Benchmarks/MyBenchmark/MyBenchmark.swift, Package.swift, Sources/Tokenizer/CharRefTokenizer.swift, Sources/Tokenizer/Tokenizer.swift, Tests/TokenizerTests/BasicHTMLTests.swift, Tests/TokenizerTests/HTML5LibTests.swift
Zyphy depends on DequeModule, so it doesn't need the other modules.
=> build: reduce dependencies

Benchmarks/Package.resolved, Benchmarks/Package.swift
release notes: https://github.com/ordo-one/package-benchmark/releases/tag/1.23.0
=> build(benchmark): bump package-benchmark to 1.23.0

Benchmarks/Benchmarks/MyBenchmark/MyBenchmark.swift, Sources/Tokenizer/CharRefTokenizer.swift, Sources/Tokenizer/Token.swift, Sources/Tokenizer/Tokenizer.swift, Sources/Tokenizer/Utils.swift, Sources/TokenizerMacros/Macros.swift, Tests/TokenizerTests/BasicHTMLTests.swift, Tests/TokenizerTests/HTML5LibTests.swift, Tests/TokenizerTests/HTML5LibTestsParser.swift
refs #61 
```
==================                                                                                                                                                                                                  
Running Benchmarks                                                                                                                                                                                                  
==================                                                                                                                                                                                                  
100% [------------------------------------------------------------] ETA: 00:00:00 | MyBenchmark:lipsum …
```
=> perf!: improve performance by replacing Character with Unicode.Scalar

Package.swift
refs #61 
This improves performance significantly. Some results are finally as fast as html5ever.
```
===================================================                                                                                                                                                                 
Comparing results between 'main' and 'Current_run'                                                                                                                                                                  
===================================================                                                                                                                                                                 
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors …
```
=> perf: enable experimental cross module optimization

Sources/Tokenizer/CharRefTokenizer.swift, Sources/Tokenizer/Tokenizer.swift
```
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors with 7 GB memory, running:
#1 SMP PREEMPT_DYNAMIC Wed Apr 24 00:11:34 UTC 2024
```
<details><summary>Time (wall clock): results within specified thresholds, fold down for details.</summary>
<p>
```
╒══════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│         Time (wall clock) (μs) *         │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │
╞══════════════════════════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│                   main                   │      16 │      16 │      16 │      16 │      16 │      17 │      17 │     100 │ …
```
=> refactor: refactor CharRefTokenizer

Sources/Tokenizer/Tokenizer.swift, Sources/TokenizerMacros/GoMacro.swift
This improves performance of `Tokenizer` by reducing reallocations.
```
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors with 7 GB memory, running:
#1 SMP PREEMPT_DYNAMIC Tue Apr 30 02:30:34 UTC 2024
```
<details><summary>Time (wall clock): results within specified thresholds, fold down for details.</summary>
<p>
```
╒══════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│         Time (wall clock) (μs) *         │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │
╞══════════════════════════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│                   main                   │      17 │      17 │      17 │      17 │      18 │ …
```
=> perf: avoid reallocations

.github/workflows/swift.yml, .octocov.yml
=> ci: fix octocov parse error (#68)

Benchmarks/Package.resolved, Benchmarks/Package.swift
https://github.com/ordo-one/package-benchmark/releases/tag/1.23.2
=> build(benchmark): bump package-benchmark to 1.23.2

Benchmarks/Package.resolved
https://github.com/apple/swift-syntax/releases/tag/510.0.2
=> build(benchmark): bump swift-syntax to 510.0.2

Sources/Tokenizer/Str.swift, Sources/Tokenizer/Tokenizer.swift
```
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors with 7 GB memory, running:
#1 SMP PREEMPT_DYNAMIC Wed May  8 18:05:42 UTC 2024
```
<details><summary>Time (wall clock): results within specified thresholds, fold down for details.</summary>
<p>
```
╒══════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│         Time (wall clock) (μs) *         │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │
╞══════════════════════════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│                   main                   │      17 │      17 │      17 │      17 │      17 │      18 │      18 │     100 │ …
```
=> feat: `Str` conforms to `ExpressibleByStringLiteral`

Package.resolved
https://github.com/apple/swift-syntax/releases/tag/600.0.0-prerelease-2024-05-14
=> build: bump swift-syntax to 6.0.0-prerelease-2024-05-14

Sources/Tokenizer/BufferQueue.swift
refs #61
```
===================================================                                                                                                                                        
Comparing results between 'main' and 'Current_run'                                                                                                                                         
===================================================                                                                                                                                        
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors with 7 GB memory, running:                                                                                                      
#1 SMP PREEMPT_DYNAMIC Fri May 17 …
```
=> perf: improve performance of `BufferQueue.pop`

Sources/Tokenizer/Str.swift
```
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors with 7 GB memory, running:
#1 SMP PREEMPT_DYNAMIC Fri May 17 17:22:13 UTC 2024
```
<details><summary>Time (wall clock): results within specified thresholds, fold down for details.</summary>
<p>
```
╒══════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│         Time (wall clock) (μs) *         │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │
╞══════════════════════════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│                   main                   │      15 │      16 │      16 │      16 │      17 │      17 │      17 │     100 │ …
```
=> refactor: refine `Str` initializers

Benchmarks/Benchmarks/MyBenchmark/Bundle+Sendable.swift, Tests/HTMLEntitiesTests/Bundle+Sendable.swift, Tests/TokenizerTests/Bundle+Sendable.swift
`Bundle` has been `Sendable` since https://github.com/apple/swift-corelibs-foundation/pull/4963, so we no longer need workarounds.
=> test: remove Bundle workarounds

Benchmarks/Package.swift, Package.swift
The latest Swift 6.0 toolchain can recognize `v6` as a known language version, so I'm going to use it.
=> chore: refactor swift language versions

.github/workflows/swift.yml
Normally, both `swift build` and `swift test` build source code. This is a waste of time. To resolve it, I've changed the CI scripts so that only `swift build` builds source code and `swift test` just runs a test executable.
- before: 4m 49s https://github.com/kkebo/zyphy/actions/runs/9353807411
- after: 2m 35s https://github.com/kkebo/zyphy/actions/runs/9465468770
references:
- https://github.com/apple/swift-package-manager/pull/7565
=> ci: avoid building twice

Sources/TreeConstructor/TreeConstructor.swift
=> fix: make TreeConstructor's TokenSink conformance public

Benchmarks/Package.resolved, Package.resolved, Package.swift
apple/swift-syntax has been moved to swiftlang/swift-syntax. So I'm updating its URLs in Package.swift and Package.resolved.
=> build: update swift-syntax to swiftlang/swift-syntax

.github/workflows/swift.yml
zyphyPackageTests.xctest and zyphyPackageTests.swift-testing are now merged into zyphyPackageTests.xctest in the latest toolchain.
=> ci: fix CI

Sources/Tokenizer/Tokenizer.swift
```                                                                                                                                                                                      
Host 'Brown-rhinoceros-beetle' with 8 'aarch64' processors with 7 GB memory, running:                                                                                                    
#1 SMP PREEMPT_DYNAMIC Sat Aug  3 22:26:24 UTC 2024                                                                                                                                      
```                                                                                                                                                                                      
<details><summary>Time (wall clock): results within …
=> perf(Tokenizer): improve performance

Sources/Tokenizer/Tokenizer.swift
I have fixed the following warning.
```
/home/kebo/zyphy/Sources/Tokenizer/Tokenizer.swift:1:8: warning: public import of 'Str' was not used in public declarations or inlinable code
1 | public import Str
|        `- warning: public import of 'Str' was not used in public declarations or inlinable code
2 | 
3 | public struct Tokenizer<Sink: ~Copyable & TokenSink>: ~Copyable {
```
=> fix: fix compiler warning

Package.resolved, Package.swift
swift-testing is now built into the toolchain, so we don't need to use the external dependencies.
=> build: use built-in swift-testing

.github/workflows/swift.yml
The CI job `build-linux` not only runs `swift build`, but also `swift test`.
=> ci: rename build-linux to test

Benchmarks/Package.resolved
https://github.com/ordo-one/package-benchmark/releases/tag/1.27.2
=> build(benchmark): bump package-benchmark to 1.27.2

.github/workflows/swift.yml
resolves #62
refs: https://swiftpackageindex.com/ordo-one/package-benchmark/main/documentation/benchmark/comparingbenchmarksci
=> ci: run benchmarks (#62)

.github/workflows/swift.yml
`swift package benchmark baseline check` may exit with status code 4 even if there are no performance regressions, but `swift package benchmark baseline compare` always returns status code 0 or 1.
=> ci: remove `set +e` from `swift package benchmark baseline compare`

.gitattributes
- Use LF
- Colorize `Package.resolved` and `.swift-format` in GitHub
- Exclude benchmark data from stats
=> chore: refine `.gitattributes`

.github/workflows/swift.yml
The “Comment PR” step of the test job is executed only when it is not on the main branch, and only the job summary is created when it is on the main branch.
=> ci: fix CI on main branch

.github/workflows/swift.yml
I added `--parallel` to `swift test`. This improves performance of test execution.
I would like to enable it if it doesn't affect code coverage.
=> ci: enable parallel test

.github/workflows/swift.yml
This change makes the CI job faster.
=> ci: add `--parallel` to swift-format

Benchmarks/Package.swift, Package.swift
This fixes [the dependabot error](https://github.com/kkebo/zyphy/actions/runs/12355959747/job/34480768869).
=> revert: build: bump swift-tools-version to 6.1

.github/workflows/swift.yml
=> ci: change Swift image to nightly-6.1-jammy

.github/workflows/swift.yml
Starting a container takes about 30 seconds. This change eliminates it.
=> ci: make comment jobs faster

Benchmarks/Package.swift, Package.swift
Swift tools version 6 uses Swift 6 language mode by default, so I don't need to specify language mode explicitly.
=> build: remove explicit language mode specifications

.swift-version, README.md
swiftly will install and use the toolchain written in `.swift-version`.
=> chore: add `.swift-version`

.github/workflows/ci.yml
swiftlang/swift:nightly-main-noble is now available, so I updated the image used in CI to it.
=> ci: use noble image

.swift-format
Some new rules have been added in Swift 6.1.
=> chore: update `.swift-format` to 6.1

Package.swift
According to [the Swift 6.1 changelog](https://github.com/swiftlang/swift/blob/main/CHANGELOG.md#swift-61),
the `ExistentialAny` flag no longer produces errors since Swift 6.1.
=> chore: enable `ExistentialAny` errors again

Benchmarks/Benchmarks/MyBenchmark/MyBenchmark.swift, Benchmarks/Package.swift, Package.swift, Sources/Tokenizer/DOCTYPE.swift, Sources/Tokenizer/Tag.swift, Sources/TokenizerMacros/GoMacro.swift, Tests/HTMLEntitiesTests/HTMLEntitiesTests.swift, Tests/TokenizerTests/HTML5LibTestsParser.swift, Tests/TreeConstructorTests/TreeConstructorTests.swift
Now, we can use [SE-0439](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0439-trailing-comma-lists.md).
=> style: add trailing commas (SE-0439)

.github/workflows/ci.yml, scripts/ci-install-swift.sh
Pros:
- We can use the latest nightly toolchain as soon as possible.
- We no longer need to worry about the gzip issue.
- CI jobs can use `.swift-version`.
Cons:
- CI execution time is a little bit longer.
=> ci: use swiftly instead of swiftlang/swift images

scripts/ci-install-swift.sh
This workaround no longer seems to be needed.
=> ci: remove a workaround for the gpg error due to gzip compression

Benchmarks/Benchmarks/MyBenchmark/MyBenchmark.swift, Benchmarks/Package.swift, Package.swift
Also, I added `.treatAllWarnings(as: .error)`. This flag helps me permanently eliminate warnings.
=> build: organize Swift settings
